// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYcM9fLf3l02NkXbf6yj_2o3Rsb1Gi4xE',
    appId: '1:580477946115:web:8b4237f4c000eba700c136',
    messagingSenderId: '580477946115',
    projectId: 'chatapp-wk-mini',
    authDomain: 'chatapp-wk-mini.firebaseapp.com',
    storageBucket: 'chatapp-wk-mini.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFetfqS7OGPrQGOXN3QZ-GGWThebQHCS0',
    appId: '1:580477946115:android:1ac32b4c8e51062b00c136',
    messagingSenderId: '580477946115',
    projectId: 'chatapp-wk-mini',
    storageBucket: 'chatapp-wk-mini.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrKcrIDizNBgPtzPgZ6bkNxdM1_nvtcpA',
    appId: '1:580477946115:ios:25183f01c020755600c136',
    messagingSenderId: '580477946115',
    projectId: 'chatapp-wk-mini',
    storageBucket: 'chatapp-wk-mini.appspot.com',
    iosBundleId: 'com.example.minimalChatWk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrKcrIDizNBgPtzPgZ6bkNxdM1_nvtcpA',
    appId: '1:580477946115:ios:25183f01c020755600c136',
    messagingSenderId: '580477946115',
    projectId: 'chatapp-wk-mini',
    storageBucket: 'chatapp-wk-mini.appspot.com',
    iosBundleId: 'com.example.minimalChatWk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYcM9fLf3l02NkXbf6yj_2o3Rsb1Gi4xE',
    appId: '1:580477946115:web:381dd7ecd28f6c5f00c136',
    messagingSenderId: '580477946115',
    projectId: 'chatapp-wk-mini',
    authDomain: 'chatapp-wk-mini.firebaseapp.com',
    storageBucket: 'chatapp-wk-mini.appspot.com',
  );
}
